server:
  port: 9080
spring:
  rabbitmq:
    addresses:  134.175.52.58
    username: guest
    password: guest
    virtual-host: /
    connection-timeout: 150000
    publisher-confirms: true
    publisher-returns: true
    template:
      mandatory: true
    listener:
      simple:
        acknowledge-mode: manual
        concurrency: 5
        max-concurrency: 10