server:
  port: 1111
eureka:
  client:
    # Eureka服务注册中心会将自己作为客户端来尝试注册它自己，必須禁止
    register-with-eureka: true #是否将自己注册到Eureka Server上，默认为true
    fetch-registry: true #是否从Eureka Server上获取注册信息，默认为true
    service-url:
      defaultZone: http://122.112.205.205:1111/eureka,http://119.3.76.241:1111/eureka,http://http://119.3.91.231:1111/eureka
  server:
    enable-self-preservation: false
