spring:
  rabbitmq:
    addresses:  134.175.52.58
    username: root
    password: root
    virtual-host: /root
    connection-timeout: 150000
    publisher-confirms: true
    publisher-returns: true
    template:
      mandatory: true